import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import NavBar from '/components/NavBar';
import Footers from '/components/Footers';
import { loadPosts } from '../lib/load-posts';

export async function getStaticProps() {
  const allPostsData = JSON.stringify(await loadPosts());
  // const allPostsDataParse = JSON.parse(allPostsData);
  // console.log(typeof('data',allPostsData));
  return {
    props: {
      allPostsData,
    },
  };
};

export default function Home({allPostsData}) {
  const parsedData = JSON.parse(allPostsData);
  return (
    <div className={styles.container}>
      <Head>
        <title>Study Ghouls</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Study Ghouls
        </h1>

        <p className={styles.description}>
          <code> One Stop Information Digital Kiosk  </code>
        </p>
        <div className={styles.gridContainerCenter}>
            <div id={styles.AreaOne}>Area 1</div>
            <div id={styles.AreaTwo}>Area 2</div>
            <div id={styles.AreaOne}>Area 3</div>
            <div id={styles.AreaOne}>Area 4</div>
            <div id={styles.AreaOne}>Area 5</div>
            <div id={styles.AreaOne}>Area 6</div>
            <div id={styles.AreaOne}>Area 7</div>
            <div id={styles.AreaOne}>Area 8</div>
            <div id={styles.AreaOne}>Area 9</div>
            <div id={styles.AreaOne}>Area 10</div>
            <div id={styles.AreaOne}>Area 11</div>
            <div id={styles.AreaOne}>Area 12</div>
            <div id={styles.AreaOne}>Area 13</div>
            <div id={styles.AreaOne}>Area 14</div>
            <div id={styles.AreaOne}>Area 15</div>
            <div id={styles.AreaOne}>Area 16</div>
        </div>
        {/* <div className={styles.grid}> */}
          {/* <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a> */}

          {/* <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a> */}

          {/* <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a> */}

          {/* <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
 
      <section>
        <h2>Blog</h2>
        <ul>
          {parsedData.map((post)=> (
            <li key={post.id}>
              {post.id}
              <br />
              {post.attributes.Title}
              <br />
              {post.attributes.Tag}
              <br />
              {post.attributes.Description}
              <br />
              {post.attributes.Tag}
              <br />
              {post.attributes.MainContent}
              <br />
              {/* {post.attributes.MainPic.} */}
            </li> 
            ))
}
           
          
           Hello
        </ul>
      </section>  

      < Footers />
    </div>
  )
}
