import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import NavBar from "/components/NavBar";
import Footers from "/components/Footers";
import { loadPosts } from "../lib/load-posts";
import Card from "/components/Card";

export async function getStaticProps() {
  const allBlogData = await loadPosts();
  // const allPostsDataParse = JSON.parse(allPostsData);
  // console.log(allBlogData);
  return {
    props: {
      data: allBlogData,
    },
  };
}

export default function Home({ data }) {
  const cardData = {
    imageSrc: "https://placeimg.com/640/480/tech",
    title: "Card Title",
    description:
      "For these courses, you will use real developer tools and software including VS Code, PostgreSQL, and the Linux / Unix command line to complete interactive tutorials and build projects.",
  };
  // const parsedData = data;
  return (
    <div className={styles.container}>
      <Head>
        <title>Study Ghouls</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Study Ghouls</h1>

        <p className={styles.description}>
          <code> One Stop Information Digital Kiosk </code>
        </p>
        <div className={styles.gridContainerCenter}>
          {data.map((post) => (
            <Card
              key={post.id}
              imageSrc={post.attributes.MainPic}
              title={post.attributes.Title}
              description={post.attributes.Description}
            />
          ))}
        </div>
      </main>

      {/* <section>
        <h2>Blog</h2>
        <ul>
          {data.map((post) => (
            <li key={post.id}>
              {post.id}
              <br />
              {post.attributes.Title}
              <br />
              {post.attributes.Tag}
              <br />
              {post.attributes.Description}
              <br />
              {post.attributes.Tag}
              <br />
              {post.attributes.MainContent}
              <br />
              {post.attributes.MainPic}
            </li>
          ))}
        </ul>
      </section> */}
      {/* <Card
        imageSrc={cardData.imageSrc}
        title={cardData.title}
        description={cardData.description}
      /> */}
    </div>
  );
}
